# Site settings
title: Hellslicer Github Page
email: hellslicer@minecorps.fr
description: > # this means to ignore newlines until "baseurl:"
  Learn from yesterday, live for today, hope for tomorrow.
  The important thing is not to stop questioning.
  -- Albert Einstein
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hellslicer.github.io" # the base hostname & protocol for your site
twitter_username: Hellslicer
github_username:  Hellslicer

# Build settings
markdown: kramdown

kramdown:
  input: GFM
